### ISSUE TITLE
Broken pipe

### ISSUE THREAD

**Issue by wkitlasten** [pypest/pyemu#333]
This is happening with an absurdly large model. But it doesn't seem like a straightforward memory error. Any suggestions? Know any plumbers?

2022-03-20 20:18:49.067189 finished: setting up pilot point parameters took: 0:05:40.160648
2022-03-20 20:20:45.115362 starting: calculating factors for pargp=ghb_pp
2022-03-20 20:20:45.115362 saving krige variance file:d:\modelling\national\si_2_s4_500_temp\ghb_inst0pp.var.dat
2022-03-20 20:20:45.115362 saving krige factors file:d:\modelling\national\si_2_s4_500_temp\ghb_inst0pp.fac
starting interp point loop for 155115 points
numpy version: 1.21.2
pandas version: 1.3.3
shapely version: 1.7.1
flopy version: 3.3.5
starting 0
numpy version: 1.21.2
pandas version: 1.3.3
shapely version: 1.7.1
flopy version: 3.3.5
starting 1
numpy version: 1.21.2
pandas version: 1.3.3
shapely version: 1.7.1
flopy version: 3.3.5
starting 2
numpy version: 1.21.2
pandas version: 1.3.3
shapely version: 1.7.1
flopy version: 3.3.5
starting 3
numpy version: 1.21.2
pandas version: 1.3.3
shapely version: 1.7.1
flopy version: 3.3.5
starting 4
numpy version: 1.21.2
pandas version: 1.3.3
shapely version: 1.7.1
flopy version: 3.3.5
starting 5
numpy version: 1.21.2
pandas version: 1.3.3
shapely version: 1.7.1
flopy version: 3.3.5
starting 6
numpy version: 1.21.2
pandas version: 1.3.3
shapely version: 1.7.1
flopy version: 3.3.5
starting 7
numpy version: 1.21.2
pandas version: 1.3.3
shapely version: 1.7.1
flopy version: 3.3.5
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated
Process Process-2:
Process Process-4:
Process Process-7:
Process Process-3:
Process Process-6:
Process Process-5:
Process Process-8:
Traceback (most recent call last):
  File "pst_from_national.py", line 349, in <module>
    build_pst_from(model)
  File "pst_from_national.py", line 77, in build_pst_from
    pp_space=pp_space0, geostruct=grid_gs0)
  File "D:\modelling\pyemu\pyemu\utils\pst_from.py", line 2476, in add_parameters
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "D:\modelling\pyemu\pyemu\utils\geostats.py", line 1485, in _worker
    idx, ix, iy = point_pairs.pop(0)
TypeError: cannot unpack non-iterable NoneType object
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\connection.py", line 312, in _recv_bytes
    nread, err = ov.GetOverlappedResult(True)
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\connection.py", line 312, in _recv_bytes
    nread, err = ov.GetOverlappedResult(True)
BrokenPipeError: [WinError 109] The pipe has been ended
BrokenPipeError: [WinError 109] The pipe has been ended

During handling of the above exception, another exception occurred:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\connection.py", line 312, in _recv_bytes
    nread, err = ov.GetOverlappedResult(True)
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\connection.py", line 312, in _recv_bytes
    nread, err = ov.GetOverlappedResult(True)
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
BrokenPipeError: [WinError 109] The pipe has been ended
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\connection.py", line 312, in _recv_bytes
    nread, err = ov.GetOverlappedResult(True)
BrokenPipeError: [WinError 109] The pipe has been ended
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\modelling\pyemu\pyemu\utils\geostats.py", line 1566, in _worker
    idist[idx] = [dist.tolist()]
BrokenPipeError: [WinError 109] The pipe has been ended

During handling of the above exception, another exception occurred:

  File "D:\modelling\pyemu\pyemu\utils\geostats.py", line 1567, in _worker
    ifacts[idx] = [facs[:-1, 0].tolist()]
Traceback (most recent call last):
  File "<string>", line 2, in __setitem__
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\connection.py", line 312, in _recv_bytes
    nread, err = ov.GetOverlappedResult(True)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 2, in __setitem__
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\managers.py", line 819, in _callmethod
    kind, result = conn.recv()
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
BrokenPipeError: [WinError 109] The pipe has been ended
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\managers.py", line 819, in _callmethod
    kind, result = conn.recv()
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "D:\modelling\pyemu\pyemu\utils\geostats.py", line 1567, in _worker
    ifacts[idx] = [facs[:-1, 0].tolist()]

During handling of the above exception, another exception occurred:

  File "D:\modelling\pyemu\pyemu\utils\geostats.py", line 1566, in _worker
    idist[idx] = [dist.tolist()]
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\connection.py", line 321, in _recv_bytes
    raise EOFError
  File "D:\modelling\pyemu\pyemu\utils\geostats.py", line 1562, in _worker
    - sum([f * c for f, c in zip(facs[:-1], interp_cov)])
  File "<string>", line 2, in __setitem__
Traceback (most recent call last):
  File "<string>", line 2, in __setitem__
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\connection.py", line 321, in _recv_bytes
    raise EOFError
EOFError
  File "<string>", line 2, in __setitem__
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\managers.py", line 819, in _callmethod
    kind, result = conn.recv()
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\managers.py", line 819, in _callmethod
    kind, result = conn.recv()
EOFError
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\managers.py", line 819, in _callmethod
    kind, result = conn.recv()
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\connection.py", line 321, in _recv_bytes
    raise EOFError
  File "D:\modelling\pyemu\pyemu\utils\geostats.py", line 1481, in _worker
    if len(point_pairs) == 0:
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\connection.py", line 321, in _recv_bytes
    raise EOFError
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\connection.py", line 321, in _recv_bytes
    raise EOFError
EOFError
  File "<string>", line 2, in __len__
EOFError
EOFError
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\managers.py", line 819, in _callmethod
    kind, result = conn.recv()
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\connection.py", line 321, in _recv_bytes
    raise EOFError
EOFError
    num_threads=10,
  File "D:\modelling\pyemu\pyemu\utils\geostats.py", line 1004, in calc_factors_grid
    num_threads=num_threads,
  File "D:\modelling\pyemu\pyemu\utils\geostats.py", line 1215, in calc_factors
    remove_negative_factors,
  File "D:\modelling\pyemu\pyemu\utils\geostats.py", line 1433, in _calc_factors_mp
    p.start()
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\ProgramData\Anaconda3\envs\py37\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
OSError: [Errno 22] Invalid argument

**Comment by briochh** [comment]
@wkitlasten looks to me like a likely memory issue. I suspect that when the datasets that are pickled up for running on the multi-process (per processor on windows) the memory explodes. Perhaps we need to look at limiting processors more or offloading to disk but both will slow down the interp...

**Comment by wkitlasten** [comment]
>
>  Perhaps we need to look at limiting processors more or offloading to disk
> but both will slow down the interp...
>

Or perhaps just limiting use to sane models. Thanks!

>
