### ISSUE TITLE
Issue with single line parameter input files in pst_from?

### ISSUE THREAD

**Issue by wkitlasten** [pypest/pyemu#371]
In the attached example, inflow1.txt and inflow2.txt have a # header plus 1 and 2 lines of parameter data, resp. (e.g. inflow from rid 1 in the first file and inflow from rid 2 and 3 in the second). The following commands add all 3 parameters to the pst obj, with appropriate (unique) obsnme:
```
pf.add_parameters(filenames='inflow1.txt', pargp='inflow1', comment_char='#', use_cols=2, index_cols=[0], upper_bound=10, lower_bound=0.1, par_type="grid")
pf.add_parameters(filenames='inflow2.txt', pargp='inflow2', comment_char='#', use_cols=2, index_cols=[0], upper_bound=10, lower_bound=0.1, par_type="grid")
```
When I run pest I get the following, and cry a little inside:
```
starting list mlt 2022-10-09 12:00:18.762882
number of chunks to process: 1
Traceback (most recent call last):
  File "forward_run.py", line 32, in <module>
    main()
  File "forward_run.py", line 26, in main
    pyemu.helpers.apply_list_and_array_pars(arr_par_file='mult2model_info.csv',chunk_len=50)
  File "C:\Users\wesk\Miniconda3\envs\py37\lib\site-packages\pyemu\utils\helpers.py", line 3647, in apply_list_and_array_pars
    apply_genericlist_pars(list_pars, chunk_len=chunk_len)
  File "C:\Users\wesk\Miniconda3\envs\py37\lib\site-packages\pyemu\utils\helpers.py", line 4160, in apply_genericlist_pars
    _process_chunk_list_files(chunks[0], 0, df)
  File "C:\Users\wesk\Miniconda3\envs\py37\lib\site-packages\pyemu\utils\helpers.py", line 4179, in _process_chunk_list_files
    raise e
  File "C:\Users\wesk\Miniconda3\envs\py37\lib\site-packages\pyemu\utils\helpers.py", line 4176, in _process_chunk_list_files
    _process_list_file(model_file, df)
  File "C:\Users\wesk\Miniconda3\envs\py37\lib\site-packages\pyemu\utils\helpers.py", line 4240, in _process_list_file
    org_data = pd.read_csv(org_file, skiprows=datastrtrow, header=header)
  File "C:\Users\wesk\Miniconda3\envs\py37\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\wesk\Miniconda3\envs\py37\lib\site-packages\pandas\io\parsers\readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\wesk\Miniconda3\envs\py37\lib\site-packages\pandas\io\parsers\readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\wesk\Miniconda3\envs\py37\lib\site-packages\pandas\io\parsers\readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "C:\Users\wesk\Miniconda3\envs\py37\lib\site-packages\pandas\io\parsers\readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "C:\Users\wesk\Miniconda3\envs\py37\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 69, in __init__
    self._reader = parsers.TextReader(self.handles.handle, **kwds)
  File "pandas\_libs\parsers.pyx", line 549, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
exit_code: 1
exception raised by run thread: GetExitCodeProcess() returned error status for command: python forward_run.py
  Error running model: GetExitCodeProcess() returned error status for command: python forward_run.py
  Aborting model run
```
If I leave out pst.add_parameters(inflow1...), pest runs, but I am 1 parameter short.

I believe the issue stems from the inflow1.txt file in tmpdir/org has no data:
`# rid type rate idx0 idx1
`
While the inflow2.txt has a faithful reproduction of the original data:
```
# rid type rate idx0 idx1
206,666,500000.0,1,1
207,666,500000.0,1,1
```

A little post-hoc manipulation to manually add the data into tmp/org/inflow1.txt and pest runs to completion.

Is there somethign about my add_parameters call that is causing issues, or something about 1 liners? I tried playing with comment_char, mfile_skip, and use_rows options but couldn't get any of them to work.

[add_par_inputs.zip](https://github.com/pypest/pyemu/files/9740461/add_par_inputs.zip)

**Comment by briochh** [comment]
Great catch @wkitlasten! 

We were initially trying to support mid-table comment lines in that add_parameters call (and possibly could do in the future). 

There was a hangover from that botched attempt that was causing issues when there were more header (or skipped lines) than data lines. 

Sorry!!!!

Working on a fix now... watch this space!
