### ISSUE TITLE
add_parameters KeyError when 'filename' includes path

### ISSUE THREAD

**Issue by wkitlasten** [pypest/pyemu#471]
Hi, I'm helping someone set up pest using pst_from. Their output files are in a subdirectory, which appears to be causing an error (or I'm messing something up!):

```
simfile = os.path.join('output', 'TroughtonFarm_daily_noavg_modelout.txt')
insfile = simfile + '.ins'
pf.add_observations(simfile, insfile=insfile, obsgp='daily', index_cols='Date',
                        use_cols=['NEP','GPP','RE','ET','VWC_10cm','NPP'])
```

The error is:
```
Traceback (most recent call last):
  File "C:\Users\wesk\AppData\Local\mambaforge\envs\py39\lib\site-packages\pandas\core\indexing.py", line 1247, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "C:\Users\wesk\AppData\Local\mambaforge\envs\py39\lib\site-packages\pandas\core\indexing.py", line 991, in _getitem_lowerdim
    return getattr(section, self.name)[new_key]
  File "C:\Users\wesk\AppData\Local\mambaforge\envs\py39\lib\site-packages\pandas\core\indexing.py", line 1073, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "C:\Users\wesk\AppData\Local\mambaforge\envs\py39\lib\site-packages\pandas\core\indexing.py", line 1301, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "C:\Users\wesk\AppData\Local\mambaforge\envs\py39\lib\site-packages\pandas\core\indexing.py", line 1239, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis)
  File "C:\Users\wesk\AppData\Local\mambaforge\envs\py39\lib\site-packages\pandas\core\indexing.py", line 1432, in _get_listlike_indexer
    keyarr, indexer = ax._get_indexer_strict(key, axis_name)
  File "C:\Users\wesk\AppData\Local\mambaforge\envs\py39\lib\site-packages\pandas\core\indexes\base.py", line 6111, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "C:\Users\wesk\AppData\Local\mambaforge\envs\py39\lib\site-packages\pandas\core\indexes\base.py", line 6171, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['oname:output\\troughtonfarm_daily_noavg_modelout.txt_otype:lst_usecol:et_date:2014-07-01',\n       'oname:output\\troughtonfarm_daily_noavg_modelout.txt_otype:lst_usecol:et_date:2014-07-02',\n       'oname:output\\troughtonfarm_daily_noavg_modelout.txt_otype:lst_usecol:et_date:2014-07-03',\n       
...
'oname:output\\troughtonfarm_daily_noavg_modelout.txt_otype:lst_usecol:vwc_10cm_date:2016-06-29'],\n      dtype='object', length=4380)] are in the [index]"
```

From pandas\core\indexes\base.py", line 6171 the key only has one `\` rather than the two `\\` mentioned in the error:

```
key
Out[1]: 
Index(['oname:output\troughtonfarm_daily_noavg_modelout.txt_otype:lst_usecol:et_date:2014-07-01',       'oname:output\troughtonfarm_daily_noavg_modelout.txt_otype:lst_usecol:et_date:2014-07-02',       'oname:output\troughtonfarm_daily_noavg_modelout.txt_otype:lst_usecol:et_date:2014-07-03',
...
```

Also from pandas\core\indexes\base.py", line 6171, there seems to be an issue with upper/lower:

```
self
Out[1]: 
Index(['oname:output\TroughtonFarm_daily_noavg_modelout.txt_otype:lst_usecol:nep_date:2014-07-01',
       'oname:output\TroughtonFarm_daily_noavg_modelout.txt_otype:lst_usecol:gpp_date:2014-07-01',
       'oname:output\TroughtonFarm_daily_noavg_modelout.txt_otype:lst_usecol:re_date:2014-07-01',
```

Any tricks for getting around this that don't involve disrupting their workflow (i.e. not requiring them to change their directory structure and/or filenames (upper/lower)?

**Comment by wkitlasten** [comment]
More clues... line 1590 in pst_from.py, new_obs in lower, df_ins with upper:

```
new_obs.index
Out[3]: 
Index(['oname:troughtonfarm_daily_noavg_modelout.txt_otype:lst_usecol:et_date:2014-07-01',
       'oname:troughtonfarm_daily_noavg_modelout.txt_otype:lst_usecol:et_date:2014-07-02',
       'oname:troughtonfarm_daily_noavg_modelout.txt_otype:lst_usecol:et_date:2014-07-03',
```

```
df_ins.index
Out[4]: 
Index(['oname:TroughtonFarm_daily_noavg_modelout.txt_otype:lst_usecol:nep_date:2014-07-01',
       'oname:TroughtonFarm_daily_noavg_modelout.txt_otype:lst_usecol:gpp_date:2014-07-01'
```

**Comment by wkitlasten** [comment]
commit d650683 seems to work, sorry I didn't branch and PR.
